### ISSUE TITLE
Telemetry unexpectedly stops transmitting

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#400] opened 2021-07-08 10:20 UTC
This is the traffic dump from before and after it gets stuck:
![image](https://user-images.githubusercontent.com/1338946/124898733-bf975880-dfdf-11eb-82d6-d7273e0d78f3.png)

Then it gets unstuck a couple hours later, reason unknown.
![image](https://user-images.githubusercontent.com/1338946/124899346-4fd59d80-dfe0-11eb-93bd-ec5d7582e640.png)

Due to sniffing location I'm only seeing the DHCP ACKs.
This only happens roughly once a week. I've seen it four times now.
It might be a timer overflow and/or race. The timescale for becoming unstuck was similar twice.

* I also wonder why all the telemetry messages are fragmented into 63 bytes.
* The MQTT connection survives the day-long stall just fine (even mid-message). But for some reason the device still resets the TCP connection after the first (successful!) telemetry message following the stall.
* No messages from the broker when the interruption start. But when it ends: 

```
1627728003: Socket error on client fls-04-91-62-d9-81-ff-tlm, disconnecting.
1627728003: New connection from 10.34.16.130 on port 1883.
1627728003: New client connected from 10.34.16.130 as fls-04-91-62-d9-81-ff-tlm (p5, c0, k0).
```

* Streaming continues unaffected throughout the interruption.
* It seems to simply mishandle the DHCP stuff. The lease time is 30 m but there is only roughly one renewal per day. When it hangs, then there are no renewals. Also when it clears there are no renewals. In fact, there are no renewals at all. Everything is just discover-off-fer-request-ack every roughly 20 hours.

**Comment by ryan-summers** [comment] 2021-07-08 11:18
My initial hunch is that there's a bug in our DHCP implementation, which tricks the network stack into thinking it no longer has an IP address. Then, any MQTT traffic fails because the nal refuses to write telemetry if there's no valid IP address assigned to the interface.

That may explain why we're seeing the DHCP acks, although I haven't looked into this yet.

**Comment by ryan-summers** [comment] 2021-08-12 11:14
In reference to the re-assembled PDUs, I've opened up an issue with smoltcp - it appears that there's a potential bug in the network stack that causes smoltcp to use the wrong TCP window size. Tracking issue is https://github.com/smoltcp-rs/smoltcp/issues/518

**Comment by jordens** [comment] 2021-08-12 12:17
The DHCP behavior still doesn't look right at all. (see above)

**Comment by ryan-summers** [comment] 2021-08-12 12:33
This appears to be caused by what I believe to be a soundness bug in the RTIC 0.7 scheduler.

Specifically, here: https://github.com/rtic-rs/cortex-m-rtic/blob/v0.5.7/src/tq.rs#L56

When the `SystemTimer` is about to wrap around, the `telemetry` task gets scheduled for the future. However, the future then wraps and overflows the timer tick. That means that the `telemetry` task is now logically "scheduled" in the past. Because of this, RTIC thinks the task is overdue and runs it _immediately_. This is why we see multiple telemetry packets immediately before the disconnect.

The downside of this is that RTIC does this in a loop, causing the task to execute _many_ times in a very short duration. This causes the telemetry task schedule to rapidly move forward until the current system time wraps around as well.

It's also possible that RTIC never sees the scheduled task (e.g. if the task is scheduled for SystemTimer::Instant::MAX, or i32::MAX). If ISR latencies or other issues cause the task queue to not process, it's possible that RTIC will "miss" a schedule if it's near the overflow point. At that point, it's not possible for the task to execute until the system timer wraps back around. In pathological cases, this causes the task execution to cease entirely.

---

In order to test this theory, I adjusted the `SystemTimer` to tick at a 10MHz rate. After ~3 minutes (the expected overflow rate with this tick rate), I saw telemetry begin to send multiple messages and then cease entirely. Network traffic shows many MQTT packets until the broker eventually disconnects the client forcibly.

![image](https://user-images.githubusercontent.com/8771450/129197304-f11c1e9e-be77-417b-b936-ffacd1e08f50.png)

**Comment by jordens** [comment] 2021-08-12 12:35
Yes. That comparison should be just checking the MSB of the wrapped difference.
I have the feeling that moving to rtic-0.6 could be very quick and easy...

**Comment by jordens** [comment] 2021-08-12 12:39
On the other hand if `Instant` implements comparison properly, then this is not a cortex-m-rtic bug but a bug in the implementor of Monotonic. Done correctly here: https://github.com/rtic-rs/cortex-m-rtic/blob/v0.5.7/src/cyccnt.rs#L110

**Comment by jordens** [comment] 2021-08-12 12:44
Not can but must. [This](https://github.com/quartiq/stabilizer/blob/master/src/hardware/system_timer.rs#L50) ist wrong.

**Comment by ryan-summers** [comment] 2021-08-12 12:46
The other option was referring to the fact we could upgrade to 0.6 - undoubtedly what we have is unsound

**Comment by jordens** [comment] 2021-08-12 12:46
Or just use the `Instant` from rtic.

**Comment by ryan-summers** [comment] 2021-08-12 13:41
As much as I'd love to, we can't construct an `Instant` because the members are private. If we use RTIC's `Instant`, we have to use the SYSTICK as the implicit timing source, which precludes us from using any telemetry duration on the order of > 5 seconds

**Comment by jordens** [comment] 2021-08-12 13:53
What about porting to rtic 0.6 instead? Might be less code alltogether.

**Comment by ryan-summers** [comment] 2021-08-12 13:54
I have nothing against that either - I'll look into what that would entail

**Comment by jordens** [comment] 2021-08-17 10:31
There is still the DHCP issue though, right?

**Comment by ryan-summers** [comment] 2021-08-17 10:32
My analysis of the logs didn't show any issue with DHCP - it appears throughout the whole capture, stabilizer had a valid IP address assignment. Did you observe other behavior?

**Comment by jordens** [comment] 2021-08-17 11:01
See above:

> It seems to simply mishandle the DHCP stuff. The lease time is 30 m but there is only roughly one renewal per day. When it hangs, then there are no renewals. Also when it clears there are no renewals. In fact, there are no renewals at all. Everything is just discover-off-fer-request-ack every roughly 20 hours.

**Comment by ryan-summers** [comment] 2021-08-17 11:47
Tracking in https://github.com/quartiq/stabilizer/issues/439 - I suspect that issue is related to system timing as well, but it would be good to double check that the lease is being respected still.

**Closed by ryan-summers** 2021-08-17 11:47 UTC
Labels: bug
