### ISSUE TITLE
[v1.1 hw] spikes on specific voltage levels

### ISSUE THREAD

**Issue by nkuh** [quartiq/stabilizer#98] opened 2020-06-10 15:21 UTC
Using the latest version of branch `feature/stabilizer/v1.1` without any changes I saw some spikes on the output signal. They occur at specific voltage levels. A sine of ~1 Vpp @ ~1 kHz was on ADC0 input.
![scope_5](https://user-images.githubusercontent.com/65332050/84286377-e36b3f00-ab3e-11ea-842e-40f56f94b1d2.png)
![scope_4](https://user-images.githubusercontent.com/65332050/84286383-e5350280-ab3e-11ea-818e-7580c74f5755.png)
![scope_3](https://user-images.githubusercontent.com/65332050/84286390-e6662f80-ab3e-11ea-9f31-5dd8911f396b.png)

**Comment by jordens** [comment] 2020-06-16 12:16
* Does it happen on both channels?
* The input signal is definitely clean?
* If you do small 10 mV amplitude around an offset close to those levels, does it occur more often?

If it's really code dependent: I think the ADC SPI clk is now twice as fast as before (v1.0). Maybe it's hitting a timing issue. I'd check slower SPI clk (25 MHz) and with a scope on the bus.

**Comment by nkuh** [comment] 2020-06-17 09:12
@ryan-summers @jordens Important update: The spikes do **not** occur at specific voltage levels. So it seems to be a timing problem. Further screenshots follow in a bit.

**Comment by nkuh** [comment] 2020-06-17 10:26
- It happens on both channels.
- Input signal is clean. 
- At small amplitude around these voltage levels it happens more often.

**Channel 0**
** 50Hz, 2 Vpp, 0 mVDC**
![scope_29](https://user-images.githubusercontent.com/65332050/84886523-d72e3700-b094-11ea-8f96-8d40952fc7da.png)

** 10Hz, 2 Vpp, 0 mVDC**
![scope_30](https://user-images.githubusercontent.com/65332050/84886609-f3ca6f00-b094-11ea-9969-d7caebbc4bed.png)

** left-hand side of previous screenshot**
![scope_31](https://user-images.githubusercontent.com/65332050/84886681-08a70280-b095-11ea-9e75-b9da7df92dd3.png)

** right-hand side of previous screenshot**
![scope_32](https://user-images.githubusercontent.com/65332050/84886835-3d1abe80-b095-11ea-86d9-b84ac687cf58.png)

** 400 Hz, 2.5 mVpp, 160.8 mVDC**
![scope_33](https://user-images.githubusercontent.com/65332050/84886940-61769b00-b095-11ea-8bda-ad757a0cc478.png)

** 400 Hz, 10 mVpp, 160.8 mVDC**
![scope_34](https://user-images.githubusercontent.com/65332050/84887034-7eab6980-b095-11ea-8742-c449a9733b72.png)
![scope_35](https://user-images.githubusercontent.com/65332050/84887049-84a14a80-b095-11ea-89f0-0fca957882b2.png)
![scope_36](https://user-images.githubusercontent.com/65332050/84887056-866b0e00-b095-11ea-943b-10a9ef8d5b53.png)
![scope_37](https://user-images.githubusercontent.com/65332050/84887067-88cd6800-b095-11ea-9ed7-660732608066.png)

**with reference signal from generator**
![scope_38](https://user-images.githubusercontent.com/65332050/84887133-a00c5580-b095-11ea-8624-84792afd57eb.png)

**same for channel 1**
![scope_39](https://user-images.githubusercontent.com/65332050/84887220-b9ad9d00-b095-11ea-8eb6-4703e9e9ec06.png)

**Ch 1, 400 Hz, 0.5 Vpp**
![scope_40](https://user-images.githubusercontent.com/65332050/84887261-c7632280-b095-11ea-9b40-f938871b4500.png)

**Comment by jordens** [comment] 2020-06-17 10:33
160 mV is exactly at the 10 bit carry toggle. My guess is ADC sample/conversion/SPI timing.

**Comment by SingularitySurfer** [comment] 2020-06-17 10:35
I think multiple spikes at low amplitudes are due to noise at the input.

**Comment by jordens** [comment] 2020-06-17 12:13
> I think multiple spikes at low amplitudes are due to noise at the input.

Noise as a root cause isn't consistent with it being triggered at a specific digital code independent of offset, amplitude, slew rate.

@nkuh 
If you want to play with the ADC SPI timing, read up on how the sampling and processing is timed and what the datasheets want, check the ADC SPI lines on a scope, and then mess with this:
https://github.com/quartiq/stabilizer/blob/547fe1bd40b010440478eafd0d09f538c9aaaa36/stabilizer/src/main.rs#L201

**Comment by SingularitySurfer** [comment] 2020-06-18 13:35
> Noise as a root cause isn't consistent with it being triggered at a specific digital code independent of offset, amplitude, slew rate.

I didn't mean as a root cause. I mean that the noise at the input causes the error, that happens at an exact voltage, to appear multiple times in quick succession because the input crosses that threshold multiple times.

**Comment by jordens** [comment] 2020-06-18 13:42
Sure. Among other things the intrinsic ADC input noise is finite. That's sufficient. But it's not the problem.

**Comment by ryan-summers** [comment] 2020-10-19 10:32
I did some investigation here and this appears to be caused by the DAC hardware when transitioning across specific binary code boundaries. Below is a capture of the CSn line (dark blue) and the stabilizer output (light blue). Note that in the middel pulse, the small spike can be seen in the negative direction immediately after the DAC code is updated.
![DS4_QuickPrint8](https://user-images.githubusercontent.com/8771450/96438136-b0306f00-1206-11eb-9e08-370e3cffb1e5.png)

Note that probing the CSn line introduces some noise on the output. Below is what the capture looks like without CSn probed:
![DS4_QuickPrint9](https://user-images.githubusercontent.com/8771450/96438409-c2aaa880-1206-11eb-9c2d-b3d843ad0f32.png)

Upon further analysis, it appears that this glitch was specifically occurring when the DAC transitions across the 10-bit boundary (e.g. from 0x83FF to 0x8400) and is transient. In the following sample, stabilizer output was modified to output 0x83FF and 0x8400 in an alternating pattern at a 50KHz update period. The SPI frequency was also lowered to 5MHz.
![DS4_QuickPrint10](https://user-images.githubusercontent.com/8771450/96439095-eff75680-1206-11eb-814a-2b8e5ba77537.png)

It can be observed that every transition causes a transient spike in the opposite direction of the transition (e.g. we get a positive spike when transitioning from 0x8400 -> 0x83FF).

This appears to be a hardware issue and there's not much we can do to mitigate this in firmware. I'm spawning an issue in the hardware repository to track this.

**Comment by ryan-summers** [comment] 2020-10-19 10:35
Because this appears to be a hardware issue, this is being continued in https://github.com/sinara-hw/Stabilizer/issues/83 and I'm closing the issue here.

**Closed by ryan-summers** 2020-10-19 10:35 UTC
Labels: bug

**Comment by jordens** [comment] 2020-10-19 12:40
Sound analysis. Is ch2 in [this shot](https://user-images.githubusercontent.com/8771450/96438136-b0306f00-1206-11eb-9e08-370e3cffb1e5.png) between DAC and output AFE opamps ro after the AFE at the SMA output?

**Comment by ryan-summers** [comment] 2020-10-19 13:13
CH2 is measured at the SMA output connected over a 50 Ohm impedance coaxial cable into the o-scope.
